CREATE DATABASE BIBLOS
USE BIBLOS

/*TABLES*/
CREATE TABLE GENRE
(
	ID INT PRIMARY KEY IDENTITY,
	_NAME VARCHAR(50) UNIQUE
)

CREATE TABLE AUTOR
(
	ID INT PRIMARY KEY IDENTITY,
	_NAME VARCHAR(50)
)

CREATE TABLE USERS
(
	ID INT PRIMARY KEY IDENTITY,
	NAME_USER VARCHAR (50) NOT NULL,
	AGE INT NOT NULL,
	_ADDRESS VARCHAR(100) NOT NULL,
	EMAIL VARCHAR (50) UNIQUE NOT NULL,
	_PASSWORD VARCHAR (15) NOT NULL,
	_ROLE VARCHAR (10) NOT NULL 
)

CREATE TABLE BOOK
(
	ID INT PRIMARY KEY IDENTITY,
	TITLE VARCHAR (100) NOT NULL,
	_DESCRIPTION VARCHAR (MAX),
	GENRE INT FOREIGN KEY REFERENCES GENRE.ID NOT NULL ,
	YEAR_PUBLICATION VARCHAR (4),
	_LANGUAGE VARCHAR (20) NOT NULL,
	READERS_AGE INT NOT NULL,
	AUTOR INT FOREIGN KEY REFERENCES AUTOR.ID NOT NULL,
	COVER_PAGE VARCHAR(100),
	QUANTITY INT DEFAULT(0),
	PRECIO FLOAT NOT NULL
)

CREATE TABLE SALES
(
	ID INT PRIMARY KEY IDENTITY,
	CLIENT INT FOREIGN KEY REFERENCES USERS.ID NOT NULL,
	BOOK INT FOREIGN KEY REFERENCES BOOK.ID NOT NULL,
	QUANTITY INT DEFAULT(1),
	TOTAL_AMOUNT FLOAT NOT NULL,
	DATE_SALE DATE NOT NULL
)

/*PROCEDURES*/


