//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblos.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.SALES = new HashSet<SALES>();
        }
    
        public int ID { get; set; }
        public string ISBN { get; set; }
        public string TITLE { get; set; }
        public string DATE_PUBLICATION { get; set; }
        public string EDITORIAL { get; set; }
        public int AUTOR { get; set; }
        public Nullable<int> STOCK { get; set; }
    
        public virtual AUTOR AUTOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES> SALES { get; set; }
    }
}
