
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Biblos.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class SALES
{

    public int ID { get; set; }

    public int CLIENT { get; set; }

    public int BOOK { get; set; }

    public Nullable<int> QUANTITY { get; set; }

    public System.DateTime DATE_SALE { get; set; }



    public virtual BOOK BOOK1 { get; set; }

    public virtual USERS USERS { get; set; }

}

}
