
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Biblos.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class USERS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public USERS()
    {

        this.SALES = new HashSet<SALES>();

    }


    public int ID { get; set; }

    public string C_NAME { get; set; }

    public string EMAIL { get; set; }

    public string C_PASSWORD { get; set; }

    public string C_ROLE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SALES> SALES { get; set; }

}

}
